library(rstudioapi)
library(dplyr) 
library(tidyverse) 
library(readxl) 
library(fastDummies) 
library(reshape2) 
library(stringr) 
library(writexl) 

library(ggraph) 
library(igraph) 
library(plotly) 
library(RColorBrewer)
library(scales)